tap "oven-sh/bun"

brew "node"
brew "oven-sh/bun/bun"
brew "pnpm"
brew "starship"
brew "stow"
cask "brainfm"

unless File.exist?(File.expand_path("~/.dotfiles/work_mode"))
  cask "appcleaner"
  cask "brave-browser"
  cask "chatgpt"
  cask "claude-code"
  cask "claude"
  cask "figma"
  cask "github"
  cask "microsoft-edge"
  cask "notion"
  cask "openra"
  cask "plex"
  cask "protonvpn"
  cask "visual-studio-code"
end
