# CLI tools
brew "bun"
brew "node"
brew "pnpm"

# Apps (Casks)
cask "appcleaner"
cask "brainfm"
cask "brave-browser"
cask "chatgpt"
cask "cursor"
cask "figma"
cask "github"
cask "google-chrome"
cask "linear-linear"
cask "notion"
cask "openra"
cask "plex"
cask "protonvpn"
cask "rive"
cask "visual-studio-code"

# VS code extensions
vscode "aaron-bond.better-comments"
vscode "bradlc.vscode-tailwindcss"
vscode "dbaeumer.vscode-eslint"
vscode "editorconfig.editorconfig"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "gruntfuggly.todo-tree"
vscode "ms-vscode.vscode-speech"
vscode "oxc.oxc-vscode"
vscode "tyriar.sort-lines"
vscode "unifiedjs.vscode-mdx"
vscode "vscode-icons-team.vscode-icons"